import { createHash, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { mkdir, open, readFile, readdir, rename, stat, unlink } from 'node:fs/promises';
import { dirname, join } from 'node:path';

export type RunImpact = 'read-only' | 'state-changing';
export type CallState = 'expected' | 'executing' | 'receipted' | 'indeterminate';
export interface ExpectedToolCall { sequence:number; callId:string; tool:string; args:unknown; nonce:string; idempotencyKey:string; state:CallState; openClawRunId?:string; leaseExpiresAt?:string }
export interface ToolReceipt { sequence:number; callId:string; tool:string; argsSha256:string; resultSha256:string; impact:'read-only'|'confirmed-mutation'; succeeded:boolean; completedAt:string }
export interface RunRecord { runId:string; bundleId:string; protocolId:string; pinsSha256:string; impact:RunImpact; receiptRequired:boolean; status:'active'|'eligible'|'violated'; nextSequence:number; expected:ExpectedToolCall[]; receipts:ToolReceipt[]; outcome?:{kind:'no-op'|'aborted';reason:string;recordedAt:string}; createdAt:string; updatedAt:string; violation?:string }
type Claims={runId:string;bundleId:string;protocolId:string;pinsSha256:string};

const canonical=(value:unknown):string=>value===null||typeof value!=='object'?JSON.stringify(value):Array.isArray(value)?`[${value.map(canonical).join(',')}]`:`{${Object.keys(value as object).sort().map(key=>`${JSON.stringify(key)}:${canonical((value as Record<string,unknown>)[key])}`).join(',')}}`;
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
const readOnlyTools=new Set(['read','memory_get','memory_search','web_fetch','get_goal','session_status','sessions_list','sessions_history']);

async function atomicWrite(path:string,value:unknown):Promise<void>{await mkdir(dirname(path),{recursive:true});const temp=`${path}.tmp-${process.pid}-${randomBytes(6).toString('hex')}`;const handle=await open(temp,'wx',0o600);try{await handle.writeFile(`${JSON.stringify(value,null,2)}\n`);await handle.sync()}finally{await handle.close()}await rename(temp,path)}

export class AtpToolGateway {
  constructor(private readonly root:string,private readonly key:Uint8Array,private readonly leaseMs=30_000){if(key.length<32)throw new Error('signing-key-too-short')}
  private runPath(id:string){if(!/^run_[a-f0-9]{32}$/.test(id))throw new Error('invalid-run-id');return join(this.root,'runs',`${id}.json`)}
  private indexPath(callId:string){return join(this.root,'call-index',`${sha(callId)}.json`)}
  private sign(payload:string){return createHmac('sha256',this.key).update(payload).digest('base64url')}
  issueToken(claims:Claims){const payload=Buffer.from(JSON.stringify({...claims,nonce:randomBytes(16).toString('hex')})).toString('base64url');return `${payload}.${this.sign(payload)}`}
  verifyToken(token:string):Claims{const [payload,signature,extra]=token.split('.');if(!payload||!signature||extra)throw new Error('token-malformed');const actual=Buffer.from(signature),expected=Buffer.from(this.sign(payload));if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new Error('token-invalid');return JSON.parse(Buffer.from(payload,'base64url').toString()) as Claims}
  async createRun(input:Claims&{impact?:RunImpact;receiptRequired?:boolean}){const now=new Date().toISOString();const run:RunRecord={...input,impact:input.impact??'state-changing',receiptRequired:input.receiptRequired??true,status:'active',nextSequence:0,expected:[],receipts:[],createdAt:now,updatedAt:now};await mkdir(dirname(this.runPath(input.runId)),{recursive:true});const handle=await open(this.runPath(input.runId),'wx',0o600);try{await handle.writeFile(JSON.stringify(run));await handle.sync()}finally{await handle.close()}return this.issueToken(input)}
  async read(id:string){return JSON.parse(await readFile(this.runPath(id),'utf8')) as RunRecord}
  async registerExpected(token:string,calls:Array<{callId:string;tool:string;args:unknown}>){const claims=this.verifyToken(token);await this.withLock(claims.runId,async()=>{const run=await this.read(claims.runId);this.requireActive(run);this.assertClaims(run,claims);for(const call of calls){if(!call.callId||!call.tool)throw new Error('call-shape-invalid');const index={callId:call.callId,runId:run.runId};await mkdir(dirname(this.indexPath(call.callId)),{recursive:true});try{const h=await open(this.indexPath(call.callId),'wx',0o600);try{await h.writeFile(JSON.stringify(index));await h.sync()}finally{await h.close()}}catch(error:any){if(error?.code==='EEXIST')throw new Error('call-id-not-unique');throw error}const sequence=run.nextSequence++;run.expected.push({sequence,callId:call.callId,tool:call.tool,args:JSON.parse(canonical(call.args)),nonce:randomBytes(16).toString('hex'),idempotencyKey:sha(`${run.runId}\0${sequence}\0${call.callId}\0${canonical(call.args)}`),state:'expected'})}run.updatedAt=new Date().toISOString();await atomicWrite(this.runPath(run.runId),run)})}
  async authorizeNativeTool(input:{openClawRunId:string;toolCallId:string;tool:string;args:unknown}){const index=JSON.parse(await readFile(this.indexPath(input.toolCallId),'utf8')) as {callId:string;runId:string};if(index.callId!==input.toolCallId)throw new Error('index-binding-invalid');return this.withLock(index.runId,async()=>{const run=await this.read(index.runId),call=run.expected.find(item=>item.callId===input.toolCallId);this.requireActive(run);if(!call||call.tool!==input.tool||canonical(call.args)!==canonical(input.args))throw new Error('not-authorized');if(call.state==='executing'&&this.leaseExpired(call)){this.violateIndeterminate(run,call);await atomicWrite(this.runPath(run.runId),run);throw new Error('execution-lease-expired')}if(call.state!=='expected')throw new Error('call-already-started');call.state='executing';call.openClawRunId=input.openClawRunId;call.leaseExpiresAt=new Date(Date.now()+this.leaseMs).toISOString();run.updatedAt=new Date().toISOString();await atomicWrite(this.runPath(run.runId),run);return{authorized:true,runId:run.runId,sequence:call.sequence,nonce:call.nonce,idempotencyKey:call.idempotencyKey,leaseExpiresAt:call.leaseExpiresAt}})}
  async heartbeatNativeTool(input:{openClawRunId:string;toolCallId:string;nonce:string}){const index=JSON.parse(await readFile(this.indexPath(input.toolCallId),'utf8')) as {runId:string};return this.withLock(index.runId,async()=>{const run=await this.read(index.runId),call=run.expected.find(item=>item.callId===input.toolCallId);this.requireActive(run);if(!call||call.state!=='executing'||call.openClawRunId!==input.openClawRunId||call.nonce!==input.nonce)throw new Error('heartbeat-binding-invalid');if(this.leaseExpired(call)){this.violateIndeterminate(run,call);await atomicWrite(this.runPath(run.runId),run);throw new Error('execution-lease-expired')}call.leaseExpiresAt=new Date(Date.now()+this.leaseMs).toISOString();run.updatedAt=new Date().toISOString();await atomicWrite(this.runPath(run.runId),run);return{ok:true,runId:run.runId,toolCallId:call.callId,leaseExpiresAt:call.leaseExpiresAt,idempotencyKey:call.idempotencyKey}})}
  async startExecution(input:{openClawRunId:string;toolCallId:string;nonce:string}){return this.heartbeatNativeTool(input)}
  async renewLease(input:{openClawRunId:string;toolCallId:string;nonce:string}){return this.heartbeatNativeTool(input)}
  async recordNativeResult(input:{openClawRunId:string;toolCallId:string;tool:string;args:unknown;result:unknown;isError?:boolean;httpStatus?:number}){const index=JSON.parse(await readFile(this.indexPath(input.toolCallId),'utf8')) as {runId:string};return this.withLock(index.runId,async()=>{const run=await this.read(index.runId),call=run.expected.find(item=>item.callId===input.toolCallId);this.requireActive(run);if(!call||call.openClawRunId!==input.openClawRunId||call.tool!==input.tool||canonical(call.args)!==canonical(input.args))throw new Error('result-binding-invalid');const resultEvidence={result:input.result,isError:!!input.isError,...input.httpStatus===undefined?{}:{httpStatus:input.httpStatus}};const resultHash=sha(canonical(resultEvidence));const prior=run.receipts.find(item=>item.sequence===call.sequence);if(prior){if(prior.resultSha256===resultHash)return prior;run.status='violated';run.violation='result-retry-diverged';await atomicWrite(this.runPath(run.runId),run);throw new Error('result-retry-diverged')}if(call.state!=='executing')throw new Error('result-without-active-execution');if(this.leaseExpired(call)){this.violateIndeterminate(run,call);await atomicWrite(this.runPath(run.runId),run);throw new Error('execution-lease-expired')}if(input.isError||((input.httpStatus??200)<200||(input.httpStatus??200)>=300)){run.status='violated';run.violation='tool-result-failed';await atomicWrite(this.runPath(run.runId),run);throw new Error('tool-result-failed')}const receipt:ToolReceipt={sequence:call.sequence,callId:call.callId,tool:call.tool,argsSha256:sha(canonical(input.args)),resultSha256:resultHash,impact:readOnlyTools.has(call.tool)?'read-only':'confirmed-mutation',succeeded:true,completedAt:new Date().toISOString()};run.receipts.push(receipt);call.state='receipted';delete call.leaseExpiresAt;run.updatedAt=new Date().toISOString();await atomicWrite(this.runPath(run.runId),run);return receipt})}
  async recordOutcome(token:string,kind:'no-op'|'aborted',reason:string){if(!reason.trim())throw new Error('outcome-reason-required');const claims=this.verifyToken(token);await this.withLock(claims.runId,async()=>{const run=await this.read(claims.runId);this.requireActive(run);this.assertClaims(run,claims);run.outcome={kind,reason,recordedAt:new Date().toISOString()};await atomicWrite(this.runPath(run.runId),run)})}
  async finalEligibility(token:string){const claims=this.verifyToken(token);return this.withLock(claims.runId,async()=>{const run=await this.read(claims.runId);this.assertClaims(run,claims);if(run.status==='violated')return{eligible:false,reason:run.violation};if(run.status!=='active')return{eligible:false,reason:'run-not-active'};if(run.receiptRequired&&run.receipts.length!==run.expected.length)return{eligible:false,reason:'receipts-incomplete'};if(run.impact==='state-changing'&&!run.receipts.some(item=>item.impact==='confirmed-mutation')&&!run.outcome)return{eligible:false,reason:'mutation-receipt-or-signed-outcome-required'};run.status='eligible';await atomicWrite(this.runPath(run.runId),run);return{eligible:true,receiptSha256:sha(canonical({receipts:run.receipts,outcome:run.outcome}))}})}
  async findReplay(request:unknown){const ids=new Set<string>();const visit=(value:unknown):void=>{if(typeof value==='string'&&value.length<512)ids.add(value);else if(Array.isArray(value))value.forEach(visit);else if(value&&typeof value==='object')Object.values(value).forEach(visit)};visit(request);const matches:RunRecord[]=[];for(const id of ids){try{const index=JSON.parse(await readFile(this.indexPath(id),'utf8')) as {callId:string;runId:string};if(index.callId===id){const run=await this.read(index.runId);if(run.status==='active'&&!matches.some(x=>x.runId===run.runId))matches.push(run)}}catch{}}if(matches.length!==1)return null;return{run:matches[0],token:this.issueToken(matches[0])}}
  async reconcile(){const violated:string[]=[];await mkdir(join(this.root,'runs'),{recursive:true});for(const name of await readdir(join(this.root,'runs'))){if(!name.endsWith('.json'))continue;const run=await this.read(name.slice(0,-5));let changed=false;for(const call of run.expected){if(call.state==='executing'&&this.leaseExpired(call)){this.violateIndeterminate(run,call);changed=true}}if(changed){await atomicWrite(this.runPath(run.runId),run);violated.push(run.runId)}else if(run.status==='violated')violated.push(run.runId)}return violated}
  private violateIndeterminate(run:RunRecord,call:ExpectedToolCall){call.state='indeterminate';delete call.leaseExpiresAt;run.status='violated';run.violation='execution-lease-expired-indeterminate';run.updatedAt=new Date().toISOString()}
  private leaseExpired(call:ExpectedToolCall){return !call.leaseExpiresAt||Date.parse(call.leaseExpiresAt)<=Date.now()}
  private assertClaims(run:RunRecord,claims:Claims){for(const key of ['runId','bundleId','protocolId','pinsSha256'] as const)if(run[key]!==claims[key])throw new Error('correlation-mismatch')}
  private requireActive(run:RunRecord){if(run.status!=='active')throw new Error('run-not-active')}
  private async withLock<T>(runId:string,fn:()=>Promise<T>):Promise<T>{const lock=`${this.runPath(runId)}.lock`;await mkdir(dirname(lock),{recursive:true});const deadline=Date.now()+5000;let handle;while(!handle){try{handle=await open(lock,'wx',0o600)}catch(error:any){if(error?.code!=='EEXIST')throw error;if(Date.now()-(await stat(lock)).mtimeMs>30_000){await unlink(lock).catch(()=>{});continue}if(Date.now()>deadline)throw new Error('run-lock-timeout');await new Promise(resolve=>setTimeout(resolve,10))}}try{return await fn()}finally{await handle.close();await unlink(lock).catch(()=>{})}}
}
