import type { IncomingMessage, ServerResponse } from 'node:http';
import type { AtpToolGateway } from '../atp/tool-gateway.js';

const MAX_BODY=256*1024;
async function readBody(req:IncomingMessage):Promise<Record<string,unknown>>{const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>MAX_BODY)throw new Error('invalid-request');chunks.push(chunk)}const value=JSON.parse(Buffer.concat(chunks).toString());if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('invalid-request');return value}
function string(value:unknown):string{if(typeof value!=='string'||value.length<1||value.length>1024)throw new Error('invalid-request');return value}
function send(res:ServerResponse,status:number,value:unknown){const bytes=Buffer.from(JSON.stringify(value));res.writeHead(status,{'content-type':'application/json','content-length':bytes.length});res.end(bytes)}
export async function handleToolGatewayApi(gateway:AtpToolGateway,req:IncomingMessage,res:ServerResponse):Promise<boolean>{
  if(req.method!=='POST'||(req.url!=='/v1/tool-policy/authorize'&&req.url!=='/v1/tool-policy/result'))return false;
  try{const body=await readBody(req);if(req.url.endsWith('/authorize')){send(res,200,await gateway.authorizeNativeTool({openClawRunId:string(body.openClawRunId),toolCallId:string(body.toolCallId),tool:string(body.tool),args:body.args??{}}));return true}send(res,200,await gateway.recordNativeResult({openClawRunId:string(body.openClawRunId),toolCallId:string(body.toolCallId),tool:string(body.tool),args:body.args??{},result:body.result,isError:body.isError===true,httpStatus:body.httpStatus===undefined?undefined:Number(body.httpStatus)}));return true}catch{send(res,409,{authorized:false,error:'tool-policy-denied'});return true}
}

export class TrustedPolicyHttpClient{constructor(private base:string,private token:string,private fetchImpl:typeof fetch=fetch){}private async post(path:string,value:unknown){const response=await this.fetchImpl(this.base+path,{method:'POST',headers:{authorization:`Bearer ${this.token}`,'content-type':'application/json'},body:JSON.stringify(value)});const body:any=await response.json();if(!response.ok)throw new Error('vectra-tool-policy-denied');return body}authorize(event:{toolName:string;params:Record<string,unknown>;toolCallId:string},ctx:{runId?:string}){if(!ctx.runId)throw new Error('run-id-missing');return this.post('/v1/tool-policy/authorize',{openClawRunId:ctx.runId,toolCallId:event.toolCallId,tool:event.toolName,args:event.params})}record(event:{toolCallId:string;toolName:string;args:Record<string,unknown>;result:unknown;isError?:boolean},ctx:{runId?:string}){if(!ctx.runId)throw new Error('run-id-missing');return this.post('/v1/tool-policy/result',{openClawRunId:ctx.runId,toolCallId:event.toolCallId,tool:event.toolName,args:event.args,result:event.result,isError:event.isError})}}
